[profile.default]
src = "src"
out = "out"
libs = ["lib"]
metadata = true
metadata_hash = "none"  # disable ipfs
use_literal_content = true # use source code

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

# Base Configuration
eth-rpc-url = "https://sepolia.base.org"
chain_id = 84532

# See more config options https://github.com/foundry-rs/foundry/blob/master/cra$